<?php

return [
    "MS_RESERVATION" => env("MS_CORPORATE_PRIORITY_RESERVATION"),
    "MS_SEAT_MAP" => env("MS_CORPORATE_PRIORITY_SEAT_MAP"),
    "MS_SEAT" => env("MS_CORPORATE_PRIORITY_SEAT"),
    "MS_EKS_AUTH" => env("MS_CORPORATE_PRIORITY_EKS_AUTH"),
    "EKS_BASIC_TOKEN" => env("CORPORATE_PRIORITY_EKS_BASIC_TOKEN"),
    "EKS_SECRET" => env("CORPORATE_PRIORITY_EKS_SECRET"),
    "MS_CORPORATE_VALIDATION" => env("MS_CORPORATE_PRIORITY_VALIDATION"),
    "MS_CONDONATE_SEATS_RESERVATION" => env("MS_CORPORATE_PRIORITY_CONDONATE_SEATS_RESERVATION"),
    "N2_AGENCY_RECORD_TYPE_ID" => env("N2_AGENCY_RECORD_TYPE_ID")
];
