<?php

return [
    "MS_RESERVATION" => env("MS_CORPORATE_PRIORITY_RESERVATION"),
    "MS_SEAT_MAP" => env("MS_CORPORATE_PRIORITY_SEAT_MAP"),
    "MS_SEAT" => env("MS_CORPORATE_PRIORITY_SEAT"),
    "MS_EKS_AUTH" => env("MS_CORPORATE_PRIORITY_EKS_AUTH"),
    "EKS_BASIC_TOKEN" => env("CORPORATE_PRIORITY_EKS_BASIC_TOKEN"),
    "EKS_SECRET" => env("CORPORATE_PRIORITY_EKS_SECRET"),
    "MS_CORPORATE_PRIORITY" => env("MS_CORPORATE_PRIORITY_RESERVATION")
];
